const peacockWordsByLang = {
  en: [
    'acclaimed',
    'addictive',
    'amazing',
    'astonishing',
    'beautiful',
    'best',
    'brilliant',
    'celebrated',
    'delicious',
    'distinguished',
    'eminent',
    'excellent',
    'exceptional',
    'exotic',
    'extraordinary',
    'famous',
    'fantastic',
    'favourite',
    'favorite',
    'finest',
    'foremost',
    'glorious',
    'great',
    'greatest',
    'ground-breaking',
    'groundbreaking',
    'heavenly',
    'iconic',
    'illustrious',
    'important',
    'impressive',
    'incomparable',
    'incredible',
    'indisputable',
    'influential',
    'innovative',
    'inspirational',
    'irresistible',
    'leading',
    'legendary',
    'luxurious',
    'magnificent',
    'majestic',
    'major',
    'notable',
    'outstanding',
    'paramount',
    'perfect',
    'pioneering',
    'popular',
    'preeminent',
    'prestigious',
    'prominent',
    'refreshing',
    'remarkable',
    'renowned',
    'respected',
    'revolutionary',
    'rich',
    'significant',
    'smooth',
    'spectacular',
    'stunning',
    'superior',
    'tasty',
    'tremendous',
    'ultimate',
    'unique',
    'unmatched',
    'unparalleled',
    'unrivalled',
    'visionary',
    'well-known',
    'wonderful',
    'world-class',
    'world-famous',
  ],
  pt: [
    'aclamado',
    'admirável',
    'belo',
    'brilhante',
    'célebre',
    'delicioso',
    'distinto',
    'emblemático',
    'excelente',
    'excecional',
    'extraordinário',
    'famoso',
    'fantástico',
    'glorioso',
    'grandioso',
    'icónico',
    'icônico',
    'ilustre',
    'impressionante',
    'incomparável',
    'incrível',
    'influente',
    'inovador',
    'inspirador',
    'lendário',
    'luxuoso',
    'magnífico',
    'majestoso',
    'maravilhoso',
    'melhor',
    'notável',
    'prestigiado',
    'proeminente',
    'reconhecido',
    'renomado',
    'revolucionário',
    'respeitado',
    'significativo',
    'sofisticado',
    'suave',
    'superior',
    'único',
    'viciante',
  ],
  tr: [
    'benzersiz',
    'büyüleyici',
    'çarpıcı',
    'değerli',
    'dikkate değer',
    'efsanevi',
    'etkileyici',
    'görkemli',
    'harika',
    'ikonik',
    'ilham verici',
    'inanılmaz',
    'kayda değer',
    'muhteşem',
    'öne çıkan',
    'öncü',
    'önemli',
    'olağanüstü',
    'parlak',
    'popüler',
    'prestijli',
    'saygın',
    'seçkin',
    'tanınmış',
    'ünlü',
  ],
}

function normalizePeacockText(text) {
  return text.normalize('NFD').replace(/\p{M}/gu, '')
}

function escapeForRegex(word) {
  return word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}

export function getPeacockWords(lang) {
  return peacockWordsByLang[lang] ?? peacockWordsByLang.en
}

export function buildPeacockPattern(words) {
  const escapedWords = words.map((word) => escapeForRegex(normalizePeacockText(word)))
  return new RegExp(`(^|[^\\p{L}\\p{N}_])(?:${escapedWords.join('|')})(?=$|[^\\p{L}\\p{N}_])`, 'iu')
}

export const peacockWords = peacockWordsByLang.en
export { normalizePeacockText }
